### PR TITLE
allow skip DirectoryTimeStamp

### PR DESCRIPTION
**Pull request by dromosys**

### CODE REVIEW

**Review by grasshopper7 — COMMENTED** [review]
1. Let's not upgrade the lombok for now. Any reason for this change?
2. Also can you replicate the same changes in pom-nexus.xml file?

**Comment by dromosys** [comment]
my mvn build failed without updating the lombok version (probably my jvm is
too new), fine to leave that

**Comment by grasshopper7** [comment]
> my mvn build failed without updating the lombok version (probably my jvm is too new), fine to leave that

What version are you using for build?

**Comment by dromosys** [comment]
using Corretto-20.0.1 I get java.lang.IllegalAccessError: class
lombok.javac.apt.LombokProcessor

**Pull request merged**
